import { jsPDF } from "jspdf";

/**
 * Generates and downloads a PDF report
 */
export const exportReportToPDF = (title: string, content: string) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxLineWidth = pageWidth - margin * 2;

  // Header - Engineering Branding
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("ENGIHUB ACADEMIC REPORT", pageWidth / 2, 20, { align: "center" });
  
  doc.setDrawColor(0, 135, 81); // Nigeria Green
  doc.line(margin, 25, pageWidth - margin, 25);

  // Title
  doc.setFontSize(14);
  doc.text(`Subject: ${title.toUpperCase()}`, margin, 35);
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Date Generated: ${new Date().toLocaleDateString()}`, margin, 42);

  // Content Body
  doc.setFontSize(11);
  const splitText = doc.splitTextToSize(content, maxLineWidth);
  doc.text(splitText, margin, 55);

  // Footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.text(
      `Generated by EngiHub Smart Assist - Page ${i}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    );
  }

  doc.save(`${title.replace(/\s+/g, "_")}_Report.pdf`);
};

/**
 * Saves a file URL to the browser cache for offline availability
 */
export const saveFileForOffline = async (fileUrl: string, fileName: string) => {
  if ('caches' in window) {
    try {
      const cache = await caches.open('engihub-offline-files');
      await cache.add(fileUrl);
      alert(`${fileName} is now available offline!`);
    } catch (err) {
      console.error("Failed to cache file:", err);
      alert(`Could not save ${fileName} for offline use.`);
    }
  } else {
    alert("Offline caching is not supported in this browser.");
  }
};
